# Generated by Django 4.0.4 on 2022-05-12 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        null=True, verbose_name="Fecha de transacción"
                    ),
                ),
                (
                    "transaction_state",
                    models.CharField(
                        choices=[
                            ("closed", "Transacción cobrada"),
                            (
                                "reversed",
                                "Cobro realizado y regresado (para validar tarjeta)",
                            ),
                            ("pending", "pendiente de cobrar"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Estado de transacción",
                    ),
                ),
                (
                    "approval_state",
                    models.BooleanField(
                        default=False, verbose_name="Estado de aprobación"
                    ),
                ),
                (
                    "payment_state",
                    models.BooleanField(default=False, verbose_name="Cobro Final"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="company.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["transaction_date"],
            },
        ),
    ]
